# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Academia
    url: /academia/
    weight: 20
  - name: Industry
    url: /industry/
    weight: 30
  - name: Publications
    url: /publications/
    weight: 35
  - name: Talks
    url: /#talks
    weight: 36
  - name: CV
    url: /uploads/cv.pdf
    weight: 40
  - name: Resume
    url: /uploads/resume.pdf
    weight: 50
